client:
  build: .
  dockerfile: Dockerfile-client
  volumes:
    - "./client:/src/app"
    - "/src/app/node_modules"
  ports:
    - "8080:8080"

node:
  build: .
  dockerfile: Dockerfile-node
  volumes:
    - "./server/node:/src/app"
    - "/src/app/node_modules"
  ports:
    - "3030:3000"